services:
  - type: web
    name: abe-garage-db
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_TYPE
        value: postgresql
      - key: FRONTEND_URL
        value: https://abe-garage-2025-tier-1.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: DB_POOL_SIZE
        value: 10
      - key: DB_POOL_MIN
        value: 2
      - key: SLOW_QUERY_THRESHOLD
        value: 1000
